### PR TITLE
Pass Through Descriptor Names for Mordred / RDKit2DDescriptors

### PR DESCRIPTION
**Pull request by Scienfitz**
## Changes

Progress for #310 
Pass through descriptor names from underlying mordred / rdkit2ddescriptor calculators via `get_feature_names_out`

## Notes
- [base class implementation](https://github.com/scikit-learn/scikit-learn/blob/a072e56fa/sklearn/base.py#L898) for reference
- [Mordred treatment of descriptor names](https://github.com/JacksonBurns/mordred-community/blob/23a3a3967968e9585b821de97ffca6095ff580d7/mordred/_base/calculator.py#L173)
- [RDKit treatment of descriptor names](https://github.com/bp-kelley/descriptastorus/blob/master/descriptastorus/descriptors/rdDescriptors.py#L439)
- Coverage: 
image

## Checklist before requesting a review
- [x] Docstrings added/updated in public functions and classes
- [x] Tests added, reasonable test coverage (at least ~90%, `make test-coverage`)
- [x] Sphinx docs added/updated and render properly (`make docs` and see `docs/_build/index.html`)

### CODE REVIEW

**Review by j-adamczyk — CHANGES_REQUESTED** [review]
Code itself looks good, tests also. But please change docstrings - they are copy-paste from scikit-learn, and some things are done differently here. In particular, you can describe what names are used as feature names.

**Comment by Scienfitz** [comment]
@j-adamczyk I've removed the call to `super` and the argument which had no purpose in the overwritten methods was kicked
This has also simplified docstrings.

Regarding a description what the feature names are: this is not going to be possible as these descriptors are large heterogeneous collections. So not sure what to do about this

**Comment by j-adamczyk** [comment]
@Scienfitz sure, removing the argument makes sense. Regarding descriptions, we don't need explicit descriptions of all features, this should also be evident from the general fingerprint documentation. However, I think it can be slightly more specific.

Currently, it is `"Get output feature names for transformation."`. It could be e.g. `"Get fingerprint feature names, i.e. names of descriptors at given columns."`. This description should work for all descriptor fingerprints (e.g. Mordred, RDKit2D).

**Review by j-adamczyk — APPROVED** [review]

**Comment by j-adamczyk** [comment]
@Scienfitz I made two small changes, everything looks nice, tests pass, so I will merge this. Thanks for the contribution!

**Pull request merged**
